### ISSUE TITLE
ModuleNotFoundError: No module named '_winreg'

### ISSUE THREAD

**Issue by ouening** [textext/textext#141]
OS: Win10
Inkscape version: 1.0 alpha2
textext version: 0.11

I installed the textext according to the instructions. And then I met the errors bellow when I use this extension:

`Traceback (most recent call last):
  File "__init__.py", line 54, in <module>
    from requirements_check import defaults, set_logging_levels, TexTextRequirementsChecker
  File "C:\Users\admin\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 772, in <module>
    defaults = WindowsDefaults()
  File "C:\Users\admin\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 92, in __init__
    import win_app_paths as wap
  File "C:\Users\admin\AppData\Roaming\inkscape\extensions\textext\win_app_paths.py", line 11, in <module>
    import _winreg as _wr
ModuleNotFoundError: No module named '_winreg'
`
 
Hope for solution for this problem, thanks.

**Comment by sizmailov** [comment]
Current release is not compatible with Inkscape 1.0+. The port in progress, take a look at #133

**Comment by sizmailov** [comment]
@ouening You can give a try to https://github.com/sizmailov/textext/tree/port_to_inkscape_1.0 from #133 with inkscape 1.0. Note: you may need to update [inkscape extensions](https://gitlab.com/inkscape/extensions) as well. 

Please let us know if it doesn't work properly.
