### ISSUE TITLE
Inkscape ha recibido información adicional del script ejecutado

### ISSUE THREAD

**Issue by angel9891** [textext/textext#197]
Por favor, me podrían ayudar con el siguiente error en Inkscape 1.0beta:

Traceback (most recent call last):
  File "__init__.py", line 54, in <module>
    from requirements_check import defaults, set_logging_levels, TexTextRequirementsChecker
  File "C:\Users\rodri\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 772, in <module>
    defaults = WindowsDefaults()
  File "C:\Users\rodri\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 92, in __init__
    import win_app_paths as wap
  File "C:\Users\rodri\AppData\Roaming\inkscape\extensions\textext\win_app_paths.py", line 11, in <module>
    import _winreg as _wr
ModuleNotFoundError: No module named '_winreg'

![image](https://user-images.githubusercontent.com/57568817/78127511-e7aa0c00-73d9-11ea-9026-36a54659a640.png)

**Comment by jcwinkler** [comment]
Most likely you installed the wrong TexText version. You need to install the development version of TexText, i.e. 1.0dev for Inkscape 1.0 beta.

Please use bug report template to give precise description of environment.

Setup for this is currently broken (see #199). Update available tomorrow.
