### ISSUE TITLE
TexText 1.0 with Inkscape 1.0 in Gentoo Linux: No module named 'inkex'

### ISSUE THREAD

**Issue by blsz** [textext/textext#224]
`python setup.py` reports no problems and built-in extensions work.  I also posted a bug with gentoo.org because I don't know where the problem lies: https://bugs.gentoo.org/722564.

```
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
    from textext.base import *
  File "/home/foo/.config/inkscape/extensions/textext/base.py", line 105, in <module>
    import inkex
ModuleNotFoundError: No module named 'inkex'
```

```
$ which inkscape
/usr/bin/inkscape

$ python --version
Python 3.7.7

$ python setup.py
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.0 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex` is found at `/usr/bin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex` is found at `/usr/bin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex` is found at `/usr/bin`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][INFO    ]: `textext/default_packages.tex` is not found in distribution, keep old file
[TexText][INFO    ]: `textext/config.json` is not found in distribution, keep old file
[TexText][INFO    ]: Removing `/home/userfoo/.config/inkscape/extensions/textext`
[TexText][INFO    ]: Creating directory `/home/userfoo/.config/inkscape/extensions/textext`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/errors.py` to `/home/userfoo/.config/inkscape/extensions/textext/errors.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/texoutparse.py` to `/home/userfoo/.config/inkscape/extensions/textext/texoutparse.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/__main__.py` to `/home/userfoo/.config/inkscape/extensions/textext/__main__.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/base.py` to `/home/userfoo/.config/inkscape/extensions/textext/base.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/__init__.py` to `/home/userfoo/.config/inkscape/extensions/textext/__init__.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/default_packages.tex` to `/home/userfoo/.config/inkscape/extensions/textext/default_packages.tex`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/win_app_paths.py` to `/home/userfoo/.config/inkscape/extensions/textext/win_app_paths.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/VERSION` to `/home/userfoo/.config/inkscape/extensions/textext/VERSION`
[TexText][INFO    ]: Creating directory `/home/userfoo/.config/inkscape/extensions/textext/icons`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-middle-right.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-middle-right.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-middle-center.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-middle-center.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-bottom-center.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-bottom-center.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/logo-32x32.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/logo-32x32.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-top-left.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-top-left.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-middle-left.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-middle-left.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-bottom-left.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-bottom-left.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-top-right.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-top-right.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/logo-16x16.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/logo-16x16.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-bottom-right.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-bottom-right.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/alignment-top-center.svg.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/alignment-top-center.svg.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/logo-128x128.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/logo-128x128.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/icons/logo-64x64.png` to `/home/userfoo/.config/inkscape/extensions/textext/icons/logo-64x64.png`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/textext.inx` to `/home/userfoo/.config/inkscape/extensions/textext/textext.inx`
[TexText][INFO    ]: Creating directory `/home/userfoo/.config/inkscape/extensions/textext/__pycache__`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/__pycache__/__init__.cpython-37.pyc` to `/home/userfoo/.config/inkscape/extensions/textext/__pycache__/__init__.cpython-37.pyc`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/__pycache__/requirements_check.cpython-37.pyc` to `/home/userfoo/.config/inkscape/extensions/textext/__pycache__/requirements_check.cpython-37.pyc`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/__pycache__/utility.cpython-37.pyc` to `/home/userfoo/.config/inkscape/extensions/textext/__pycache__/utility.cpython-37.pyc`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/__pycache__/errors.cpython-37.pyc` to `/home/userfoo/.config/inkscape/extensions/textext/__pycache__/errors.cpython-37.pyc`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/asktext.py` to `/home/userfoo/.config/inkscape/extensions/textext/asktext.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/requirements_check.py` to `/home/userfoo/.config/inkscape/extensions/textext/requirements_check.py`
[TexText][INFO    ]: Copying `/home/userfoo/tmp/textext/textext-1.0.0/textext/utility.py` to `/home/userfoo/.config/inkscape/extensions/textext/utility.py`
[TexText][SUCCESS ]: --> TexText has been SUCCESSFULLY installed on your system <--
```

**Comment by blsz** [comment]
Gentoo media-gfx/inkscape-1.0 no longer provides /usr/share/inkscape/extensions/inkex.py.   This issue can probably be closed unless the inkex module is supposed to be provided elsewhere in inkscape-1.0.

**Comment by jcwinkler** [comment]
Inkscape and its extension are developed in separate projects since 1.0:
- Inkscape: https://gitlab.com/inkscape/inkscape
- Inkscape extensions: https://gitlab.com/inkscape/extensions

Extensions project is a submodule in inkscape, so usually the package maintainer should pull the submodule before building the packages, see https://inkscape.org/develop/getting-started/
