### ISSUE TITLE
'lxml.etree._Element' object has no attribute 'bounding_box'

### ISSUE THREAD

**Issue by bheijden** [textext/textext#227]
Hi all,

Yesterday, suddenly the TexText extension stopped working. First it gave me the message that it could not find the correct python version (2.7), and found 3.6.xx instead. I was able to resolve this error message via [this link](https://stackoverflow.com/questions/52046845/changing-the-python-interpreter-for-inkscape), where they instruct you to add a line to Inkscape's preferences.xml about the python-interpreter. Nonetheless, it is strange that it was working, but suddenly decided to use a different python version. Though, I remember doing a regular Ubuntu update just before it broke down (was using textext while performing the Ubuntu update). 

After adding the line in the preferences.xml, Textext found the correct python version (2.7) and I was able to open the extension in inkscape. However when inputting something simple like $\theta$, a TexText Error box opened, saying 

> "Error occurred while converting text from Latex to SVG: "'lxml.etree._Element' object has no attribute 'bounding_box'". 

Subsequently closing the TexText editor resulted in 

<details>
<summary>Inkscape error message:</summary>

```
> __init__.py:175: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
__init__.py:179: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
__init__.py:183: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
__init__.py:1156: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
__init__.py:218: DeprecationWarning: Effect.unittouu is now a method in the svg document. Use `self.svg.unittouu(str)` instead.
  return self.unittouu(unit)
__init__.py:842: DeprecationWarning: simplestyle.parseStyle -> dict(inkex.Style.parse_str(s))
  node_style_dict = ss.parseStyle(node.attrib["style"])
__init__.py:845: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  node.attrib["style"] = ss.formatStyle(node_style_dict)
__init__.py:916: DeprecationWarning: simpletransform.computeBBox -> sum([node.bounding_box() for node in aList])
  min_x, max_x, min_y, max_y = st.computeBBox([self._node], mat)
```
</details>

The textext.log contains the following, where it appears that the error first occurs at the highlighted parts. Any idea what the problem might be?

<details>
<summary>textext.log:</summary>

```
> [2020-05-14 15:31:53,902][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.          //  __init__.py:141  
[2020-05-14 15:31:53,902][DEBUG   ]: TexText initialized          //  __init__.py:150  
[2020-05-14 15:31:53,902][DEBUG   ]: TexText version = '0.11.0' (md5sum = cdd7dc145364a80a56fdaa5c84096461)          //  __init__.py:152  
[2020-05-14 15:31:53,902][DEBUG   ]: platform.system() = 'Linux'          //  __init__.py:154  
[2020-05-14 15:31:53,902][DEBUG   ]: platform.release() = '5.3.0-51-generic'          //  __init__.py:155  
[2020-05-14 15:31:53,902][DEBUG   ]: platform.version() = '#44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020'          //  __init__.py:156  
[2020-05-14 15:31:53,902][DEBUG   ]: platform.machine() = 'x86_64'          //  __init__.py:158  
[2020-05-14 15:31:53,902][DEBUG   ]: platform.uname() = ('Linux', 'bas-Alienware-m15-R2', '5.3.0-51-generic', '#44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020', 'x86_64', 'x86_64')          //  __init__.py:159  
[2020-05-14 15:31:53,902][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')          //  __init__.py:160  
[2020-05-14 15:31:53,902][DEBUG   ]: sys.executable = '/usr/bin/python'          //  __init__.py:162  
[2020-05-14 15:31:53,902][DEBUG   ]: sys.version = '2.7.17 (default, Apr 15 2020, 17:20:14) \n[GCC 7.5.0]'          //  __init__.py:163  
[2020-05-14 15:31:53,902][DEBUG   ]: os.environ = {'LC_NUMERIC': 'nl_NL.UTF-8', 'PYTHONIOENCODING': 'UTF-8', 'QT4_IM_MODULE': 'xim', 'GJS_DEBUG_OUTPUT': 'stderr', 'LC_MEASUREMENT': 'nl_NL.UTF-8', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'XDG_SESSION_TYPE': 'x11', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'bas', 'XDG_SEAT': 'seat0', 'PATH': '/usr/bin:/home/bas/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '2', 'HOME': '/home/bas', 'DISPLAY': ':0', 'SSH_AGENT_PID': '2837', 'LANG': 'en_US.UTF-8', 'SHELL': '/bin/bash', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SESSION_MANAGER': 'local/bas-Alienware-m15-R2:@/tmp/.ICE-unix/2741,unix/bas-Alienware-m15-R2:/tmp/.ICE-unix/2741', 'LC_MONETARY': 'nl_NL.UTF-8', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'CLUTTER_IM_MODULE': 'xim', 'TEXTDOMAIN': 'im-config', 'QT_ACCESSIBILITY': '1', 'WINDOWPATH': '2', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'IM_CONFIG_PHASE': '2', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '8720', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'USERNAME': 'bas', 'XDG_SESSION_DESKTOP': 'ubuntu', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/org.inkscape.Inkscape.desktop', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_IDENTIFICATION': 'nl_NL.UTF-8', 'LC_ADDRESS': 'nl_NL.UTF-8', 'PYTHONPATH': '/home/bas/.config/inkscape/extensions:/usr/share/inkscape/extensions:/usr/share/inkscape/extensions/inkex/deprecated-simple', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'GDMSESSION': 'ubuntu', 'XMODIFIERS': '@im=ibus', 'TEXTDOMAINDIR': '/usr/share/locale/', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'XDG_SESSION_ID': '2', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'GTK_IM_MODULE': 'ibus', 'DESKTOP_SESSION': 'ubuntu', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'GTK_MODULES': 'gail:atk-bridge', 'INKEX_GETTEXT_DIRECTORY': '/usr/share/locale', 'LC_TELEPHONE': 'nl_NL.UTF-8', 'SHLVL': '0', 'PWD': '/home/bas', 'LC_PAPER': 'nl_NL.UTF-8', 'LC_NAME': 'nl_NL.UTF-8', 'XDG_MENU_PREFIX': 'gnome-', 'LC_TIME': 'nl_NL.UTF-8', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'USER': 'bas'}          //  __init__.py:164  
[2020-05-14 15:31:53,986][SUCCESS ]: + [Succ] TexText requirements          //  requirements_check.py:764  
[2020-05-14 15:31:53,986][SUCCESS ]: /-and-* [Succ] Detect inkscape          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |      `inkscape` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |      `inkscape` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: /-and-* [Succ] Detect `python2.7`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |      python2.7 is found at `/usr/bin/python`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: /-and-+ [Succ] Detect *latex          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |     /--or-* [Succ] `pdflatex` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |     |      `pdflatex` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |     /--or-* [Succ] `lualatex` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |     |      `lualatex` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |     /--or-* [Succ] `xelatex` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |            `xelatex` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: /-and-+ [Succ] Detect GUI library          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: |     /--or-* [Succ] PyGTK2 is found          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][INFO    ]: |     /--or-* [Fail] TkInter is not found          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][INFO    ]: |            Please follow installation instructions at           //  requirements_check.py:335  
[2020-05-14 15:31:53,987][INFO    ]: |                   [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-tkinter[0m          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][SUCCESS ]: /-and-+ [Succ] Detect pdf->svg conversion utility          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][INFO    ]:       /--or-+ [Fail] Detect compatible pstoedit+ghostscript versions          //  requirements_check.py:335  
[2020-05-14 15:31:53,987][INFO    ]:       |      Please follow installation instructions at           //  requirements_check.py:335  
[2020-05-14 15:31:53,987][INFO    ]:       |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-pstoedit[0m          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][SUCCESS ]:       |     /-and-+ [Succ]           //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |     /-not-+ [Fail] Detect incompatible versions of pstoedit+ghostscript          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |           /--or-+ [Fail]           //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |           |     /-and-* [Fail] pstoedit=3.70 is not found          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |           |     /-and-* [Fail] ghostscript=9.22 is not found (but ghostscript=9.26 is found)          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |           /--or-+ [Fail]           //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |                 /-and-* [Fail] pstoedit=3.74 is not found          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |                 /-and-* [Fail] ghostscript=9.27 is not found (but ghostscript=9.26 is found)          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     /-and-* [Fail] pstoedit is not found          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |      Please follow installation instructions at           //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |             [94m[4mhttps://textext.github.io/textext/install/linux.html#linux-install-pstoedit[0m          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |      If pstoedit is installed in custom location, specify it via           //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |             --pstoedit-executable=<path-to-pstoedit>          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][INFO    ]:       |     |      and run setup.py again          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][SUCCESS ]:       |     /-and-* [Succ] ghostscript is found          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][SUCCESS ]:       /--or-* [Succ] Detect pdf2svg:          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][SUCCESS ]:              `pdf2svg` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:53,988][SUCCESS ]:              `pdf2svg` is found at `/usr/bin`          //  requirements_check.py:335  
[2020-05-14 15:31:54,039][DEBUG   ]: TexText.effect          //  __init__.py:237  
[2020-05-14 15:31:54,039][DEBUG   ]:   Pdf2SvgPlotSvg is usable          //  __init__.py:246  
[2020-05-14 15:31:54,039][DEBUG   ]:   Can't adjust scale to account node transformations done in inkscape. May result in loss of scale.          //  __init__.py:270  
[2020-05-14 15:31:54,039][DEBUG   ]:   Using default node alignment `middle center`          //  __init__.py:279  
[2020-05-14 15:31:54,039][DEBUG   ]:   Using default tex converter `pdflatex`           //  __init__.py:291  
[2020-05-14 15:31:54,039][DEBUG   ]:   Using default preamble file `default_packages.tex`          //  __init__.py:300  
[2020-05-14 15:31:54,039][DEBUG   ]:   Run TexText GUI          //  __init__.py:340  
[2020-05-14 15:32:00,281][DEBUG   ]:     TexText.do_convert          //  __init__.py:424  
[2020-05-14 15:32:00,281][DEBUG   ]:       args:          //  __init__.py:425  
[2020-05-14 15:32:00,281][DEBUG   ]:         converter = <__main__.Pdf2SvgPlotSvg object at 0x7f69c9cbd290>          //  __init__.py:427  
[2020-05-14 15:32:00,281][DEBUG   ]:         original_scale = None          //  __init__.py:427  
[2020-05-14 15:32:00,282][DEBUG   ]:         text = '$\\theta$'          //  __init__.py:427  
[2020-05-14 15:32:00,282][DEBUG   ]:         tex_command = 'pdflatex'          //  __init__.py:427  
[2020-05-14 15:32:00,282][DEBUG   ]:         preamble_file = '/home/bas/.config/inkscape/extensions/textext/default_packages.tex'          //  __init__.py:427  
[2020-05-14 15:32:00,282][DEBUG   ]:         user_scale_factor = 1.0          //  __init__.py:427  
[2020-05-14 15:32:00,282][DEBUG   ]:         old_svg_ele = None          //  __init__.py:427  
[2020-05-14 15:32:00,283][DEBUG   ]:         tex_executable = '/usr/bin/pdflatex'          //  __init__.py:427  
[2020-05-14 15:32:00,283][DEBUG   ]:         self = <__main__.TexText object at 0x7f69c9aed810>          //  __init__.py:427  
[2020-05-14 15:32:00,283][DEBUG   ]:         alignment = 'middle center'          //  __init__.py:427  
[2020-05-14 15:32:00,283][DEBUG   ]:       args: done          //  __init__.py:427  
[2020-05-14 15:32:00,284][DEBUG   ]:       Converting tex to svg          //  __init__.py:441  
[2020-05-14 15:32:00,284][DEBUG   ]:         Converting .tex to svg element          //  __init__.py:659  
[2020-05-14 15:32:00,286][DEBUG   ]:           Converting .tex to .pdf          //  __init__.py:595  
[2020-05-14 15:32:00,314][DEBUG   ]:           Converting .tex to .pdf done          //  __init__.py:625  
[2020-05-14 15:32:00,315][DEBUG   ]:           Converting .pdf to .svg          //  __init__.py:780  
[2020-05-14 15:32:00,322][DEBUG   ]:           Converting .pdf to .svg done          //  __init__.py:786  
[2020-05-14 15:32:00,322][DEBUG   ]:           Groupping resulting svg          //  __init__.py:801  
[2020-05-14 15:32:00,322][DEBUG   ]:           Groupping resulting svg done          //  __init__.py:848  
[2020-05-14 15:32:00,323][DEBUG   ]:         Converting .tex to svg element done          //  __init__.py:669  
[2020-05-14 15:32:00,323][DEBUG   ]:       Converting tex to svg done          //  __init__.py:442  
[2020-05-14 15:32:00,323][DEBUG   ]:       Adding new node to document          //  __init__.py:461  
**[2020-05-14 15:32:00,323][DEBUG   ]:       Adding new node to document failed          //  __init__.py:470**  
**[2020-05-14 15:32:00,323][DEBUG   ]:     TexText.do_convert failed          //  __init__.py:496**  
[2020-05-14 15:32:02,128][DEBUG   ]:     TexText.do_convert          //  __init__.py:424  
[2020-05-14 15:32:02,129][DEBUG   ]:       args:          //  __init__.py:425  
[2020-05-14 15:32:02,129][DEBUG   ]:         converter = <__main__.Pdf2SvgPlotSvg object at 0x7f69c9cbd290>          //  __init__.py:427  
[2020-05-14 15:32:02,129][DEBUG   ]:         original_scale = None          //  __init__.py:427  
[2020-05-14 15:32:02,130][DEBUG   ]:         text = '$\\theta$'          //  __init__.py:427  
[2020-05-14 15:32:02,130][DEBUG   ]:         tex_command = 'pdflatex'          //  __init__.py:427  
[2020-05-14 15:32:02,130][DEBUG   ]:         preamble_file = '/home/bas/.config/inkscape/extensions/textext/default_packages.tex'          //  __init__.py:427  
[2020-05-14 15:32:02,130][DEBUG   ]:         user_scale_factor = 1.0          //  __init__.py:427  
[2020-05-14 15:32:02,130][DEBUG   ]:         old_svg_ele = None          //  __init__.py:427  
[2020-05-14 15:32:02,131][DEBUG   ]:         tex_executable = '/usr/bin/pdflatex'          //  __init__.py:427  
[2020-05-14 15:32:02,131][DEBUG   ]:         self = <__main__.TexText object at 0x7f69c9aed810>          //  __init__.py:427  
[2020-05-14 15:32:02,131][DEBUG   ]:         alignment = 'middle center'          //  __init__.py:427  
[2020-05-14 15:32:02,131][DEBUG   ]:       args: done          //  __init__.py:427  
[2020-05-14 15:32:02,132][DEBUG   ]:       Converting tex to svg          //  __init__.py:441  
[2020-05-14 15:32:02,132][DEBUG   ]:         Converting .tex to svg element          //  __init__.py:659  
[2020-05-14 15:32:02,132][DEBUG   ]:           Converting .tex to .pdf          //  __init__.py:595  
[2020-05-14 15:32:02,174][DEBUG   ]:           Converting .tex to .pdf done          //  __init__.py:625  
[2020-05-14 15:32:02,174][DEBUG   ]:           Converting .pdf to .svg          //  __init__.py:780  
[2020-05-14 15:32:02,181][DEBUG   ]:           Converting .pdf to .svg done          //  __init__.py:786  
[2020-05-14 15:32:02,182][DEBUG   ]:           Groupping resulting svg          //  __init__.py:801  
[2020-05-14 15:32:02,182][DEBUG   ]:           Groupping resulting svg done          //  __init__.py:848  
[2020-05-14 15:32:02,182][DEBUG   ]:         Converting .tex to svg element done          //  __init__.py:669  
[2020-05-14 15:32:02,182][DEBUG   ]:       Converting tex to svg done          //  __init__.py:442  
[2020-05-14 15:32:02,182][DEBUG   ]:       Adding new node to document          //  __init__.py:461  
**[2020-05-14 15:32:02,183][DEBUG   ]:       Adding new node to document failed          //  __init__.py:470**  
**[2020-05-14 15:32:02,183][DEBUG   ]:     TexText.do_convert failed          //  __init__.py:496**  
[2020-05-14 15:32:04,013][DEBUG   ]:   Run TexText GUI done          //  __init__.py:341  
[2020-05-14 15:32:04,013][DEBUG   ]:   Saving global GUI settings          //  __init__.py:343  
[2020-05-14 15:32:04,013][DEBUG   ]:   Saving global GUI settings done          //  __init__.py:345  
[2020-05-14 15:32:04,013][DEBUG   ]: TexText.effect done          //  __init__.py:357  

```
</details>

Via the Inkscape menu GUI-->Help-->About Inkscape I see version 1.0 (1.0+r73).

**Comment by jcwinkler** [comment]
(@bheijden I updated your comment so it is better readable)

Which Inkscape version are you using?

**Comment by bheijden** [comment]
@jcwinkler much better, thank you. First time I post an issue anywhere on Github so not yet familiar with Github's markup options. I updated my first post with the version.

**Comment by jcwinkler** [comment]
You are using TexText 0.11. This version is incompatible with Inkscape 1.0 Please update TexText to verison 1.0.1: https://github.com/textext/textext/releases

**Comment by bheijden** [comment]
Solved it! Now that I take a closer look at inkscape, some icons seem to have changed. Can it be that Ubuntu upgraded the Inkscape version yesterday wihtout explicit consent?

Nevertheless, thank you very much for the quick reply.

**Comment by jcwinkler** [comment]
Good to hear that the problem has been solved.

> Can it be that Ubuntu upgraded the Inkscape version yesterday wihtout explicit consent?

It seems so. Have you installed Inkscape via `apt-get` or `ppa` originally?

**Comment by bheijden** [comment]
Hi, somehow TexText stopped working again. My Inkscape version is still 1.0 but the numbers in the parenthesis did change, namely to 1.0 (1.0+r73+1). Does the addition of the +1 at the end mean that it is a newer version of Inkscape? I must have automatically upgraded my inkscape again... I think I installed it via apt-get.

**Comment by sizmailov** [comment]
@bheijden You have broken installation of inkscape. `lxml` should be importable.

**Comment by bheijden** [comment]
@sizmailov Reinstalling Inkscape did the trick. Thank you!

**Comment by bheijden** [comment]
I do not know what I am doing wrong... Somehow TexText stopped working again. I am sure I did not update inkscape in the meantime... I've completely removed inkscape, and then reinstalled inkscape by following [this ppa procedure](https://inkscape.org/release/inkscape-1.0.1/gnulinux/ubuntu/ppa/dl/). I also reinstalled textext, but to no avail. I keep getting the error below. The Inkscape version that was installed is (1.0.1+r73).

I am under a fairly strict deadline, so any help is greatly appreciated! 

<details>
<summary>Inkscape error message:</summary>

```
>Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
    from textext.base import *
  File "/home/bas/.config/inkscape/extensions/textext/base.py", line 105, in <module>
    import inkex
  File "/usr/share/inkscape/extensions/inkex/__init__.py", line 11, in <module>
    from .extensions import *
  File "/usr/share/inkscape/extensions/inkex/extensions.py", line 33, in <module>
    from .elements import load_svg, BaseElement, ShapeElement, Group, Layer, Grid, \
  File "/usr/share/inkscape/extensions/inkex/elements/__init__.py", line 8, in <module>
    from ._base import SVG_PARSER, load_svg, ShapeElement, BaseElement
  File "/usr/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module>
    from lxml import etree
ImportError: No module named lxml
```
</details>

**Comment by jcwinkler** [comment]
The python distro seems to be broken. Assuming you are still under Ubuntu 18.04 as in the OP please try:

```bash
sudo apt install libxml2-utils
sudo apt install python-lxml
```

**Comment by bheijden** [comment]
Reinstalling the mentioned packages worked. I am truly puzzled why the python distro broke down.. Nonetheless, many thanks @jcwinkler, you saved the day :)!
