### ISSUE TITLE
Linux: Installation does not see GTK3 although packages installed

### ISSUE THREAD

**Issue by lefterav** [textext/textext#267]
**Description of the problem/ steps to reproduce**
The documentation instructs that one should first install a set of packages, including the ones for GTK3 and then run the installation. The installer should be able to detect the GTK3 packages and include them. Unfortunately in my clean installation at Ubuntu 20.04 did not happen. I got the warning that GTK3 is not found and TkInter was used instead. 
**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>output of stdout (if available):</summary>

```
sudo apt-get install python3-gi gir1.2-gtk-3.0 gir1.2-gtksource-3.0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.36.0-1).
gir1.2-gtksource-3.0 is already the newest version (3.24.11-2).
gir1.2-gtk-3.0 is already the newest version (3.24.20-0ubuntu1).
The following packages were automatically installed and are no longer required:
  libgtkmm-2.4-1v5 libgtkspell0 python-backports.functools-lru-cache
  python-bs4 python-chardet python-html5lib python-lxml python-numpy
  python-pkg-resources python-scour python-six python-soupsieve
  python-webencodings scour
```

```
/-and-+ [Succ] Detect GUI library
[TexText][INFO    ]:       /--or-* [Fail] GTK3 is not found
[TexText][INFO    ]:       |      Please follow installation instructions at 
[TexText][INFO    ]:       |             https://textext.github.io/textext/install/linux.html#linux-install-gtk3
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found


```
</details>

**Comment by mattfack** [comment]
In my case the third line fails with 

`** (process:25774): WARNING **: 19:29:10.303: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
`

**Comment by mattfack** [comment]
btw @jcwinkler you could extend the title to unix systems: I am a Mac user

**Comment by sizmailov** [comment]
@mattfack First, the installation problems are usually system-dependent (or at least requires system-dependent solutions). Second, we need to see the output of @lefterav to figure out root cause of error ("GTK is not working" is too broad).

**Comment by mattfack** [comment]
After exporting DYLD_LIBRARY_PATH I managed to make all the three commands work on my system python3

Unfortunately textext would not start due to the same error (from the log):

    [Fail] GTK3 is not found

**Comment by sizmailov** [comment]
> After exporting DYLD_LIBRARY_PATH I managed to make all the three commands proposed by @jcwinkler work on my system python3

This means you installed some libraries in a custom location (i.e. the one not searched by default for shared libraries). You need to install in the locations that _are_ searched for dyn libraries (preferably) or (more shortcoming) export DYLD_LIBRARY_PATH in startup scripts (probably `~/.profile` is the one). 

You can make inkscape use desired python by [altering inkscape preferences](https://textext.github.io/textext/textext_0x/usage/faq.html?highlight=interpreter#set-inkscape-python-interpreter-to-python2)

**Comment by mattfack** [comment]
since `echo $DYLD_LIBRARY_PATH ` produced no output I already did as you suggested, I also changed inkscape preferences and now, after a clean install I have a new error!

    
    
    ** (process:22488): WARNING **: 13:13:30.562: Failed to load shared library 'libgobject-2.0.0.dylib' referenced by the typelib: dlopen(libgobject-2.0.0.dylib, 9): no suitable image found.  Did find:
    	/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/libgobject-2.0.0.dylib: mach-o, but wrong architecture
    	/Applications/Inkscape.app/Contents/Resources/lib/libgobject-2.0.0.dylib: mach-o, but wrong architecture    

    ** (process:22488): WARNING **: 13:13:30.563: Failed to load shared library 'libglib-2.0.0.dylib' referenced by the typelib: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
    	/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture
    	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture
    [TexText][DEBUG   ]: Enforcing DEBUG mode due to previous exit code `60`
    [TexText][DEBUG   ]: TexText initialized
    [TexText][DEBUG   ]: TexText version = '1.3.0' (md5sum = 110c558157a2b3537550f854fa686d85)
    [TexText][DEBUG   ]: platform.system() = 'Darwin'
    [TexText][DEBUG   ]: platform.release() = '20.2.0'
    [TexText][DEBUG   ]: platform.version() = 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101'
    [TexText][DEBUG   ]: platform.machine() = 'arm64'
    [TexText][DEBUG   ]: platform.uname() = uname_result(system='Darwin', node='MBP-di-Matteo.home-life.hub', release='20.2.0', version='Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101', machine='arm64')
    [TexText][DEBUG   ]: platform.mac_ver() = ('11.1', ('', '', ''), 'arm64')
    [TexText][DEBUG   ]: sys.executable = '/opt/homebrew/opt/python@3.9/bin/python3.9'
    [TexText][DEBUG   ]: sys.version = '3.9.1 (default, Jan  8 2021, 12:11:08) \n[Clang 12.0.0 (clang-1200.0.32.28)]'
    [TexText][DEBUG   ]: os.environ = environ({'USER': 'username', '__CFBundleIdentifier': 'org.inkscape.Inkscape', 'COMMAND_MODE': 'unix2003', 'DISPLAY': '/private/tmp/com.apple.launchd.1cfEVrCWr0/org.macosforge.xquartz:0', 'LOGNAME': 'username', 'PATH': '/Applications/Inkscape.app/Contents/MacOS:/Applications/Inkscape.app/Contents/MacOS/../Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.p2kItK1Mzp/Listeners', 'SHELL': '/bin/zsh', 'HOME': '/Users/username', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x4', 'TMPDIR': '/var/folders/_f/lrf33ym56gn2h_6wdqlcyp5w0000gn/T/', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'XDG_DATA_HOME': '/Users/username/Library/Application Support/org.inkscape.Inkscape/share', 'XDG_DATA_DIRS': '/Applications/Inkscape.app/Contents/MacOS/../Resources/share', 'XDG_CONFIG_HOME': '/Users/username/Library/Application Support/org.inkscape.Inkscape/config', 'XDG_CONFIG_DIRS': '/Applications/Inkscape.app/Contents/MacOS/../Resources/etc/xdg', 'XDG_CACHE_HOME': '/Users/username/Library/Application Support/org.inkscape.Inkscape/cache', 'GTK_EXE_PREFIX': '/Applications/Inkscape.app/Contents/MacOS/../Resources', 'GTK_DATA_PREFIX': '/Applications/Inkscape.app/Contents/MacOS/../Resources', 'GDK_PIXBUF_MODULE_FILE': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache', 'INKSCAPE_LOCALEDIR': '/Applications/Inkscape.app/Contents/MacOS/../Resources/share/locale', 'FONTCONFIG_PATH': '/Applications/Inkscape.app/Contents/MacOS/../Resources/etc/fonts', 'GIO_MODULE_DIR': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/gio/modules', 'GI_TYPELIB_PATH': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/girepository-1.0', 'DYLD_LIBRARY_PATH': '/Applications/Inkscape.app/Contents/MacOS/../Resources/lib:/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders', 'PYTHONPATH': '/Users/username/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated-simple', 'PYTHONIOENCODING': 'UTF-8', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKEX_GETTEXT_DIRECTORY': '/Applications/Inkscape.app/Contents/MacOS/../Resources/share/locale', 'LC_CTYPE': 'UTF-8'})
    [TexText][INFO    ]: Using `pdflatex-executable` = `/Library/TeX/texbin/pdflatex`
    [TexText][INFO    ]: Using `lualatex-executable` = `/Library/TeX/texbin/lualatex`
    [TexText][INFO    ]: Using `xelatex-executable` = `/Library/TeX/texbin/xelatex`
    [TexText][SUCCESS ]: + [Succ] TexText requirements
    [TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
    [TexText][SUCCESS ]: |      inkscape=1.0 is found
    [TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
    [TexText][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/Library/TeX/texbin/pdflatex`
    [TexText][SUCCESS ]: |     /--or-* [Succ] lualatex is found at `/Library/TeX/texbin/lualatex`
    [TexText][SUCCESS ]: |     /--or-* [Succ] xelatex is found at `/Library/TeX/texbin/xelatex`
    [TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
    [TexText][INFO    ]:       /--or-* [Fail] GTK3 is not found
    [TexText][INFO    ]:       |      Please follow installation instructions at 
    [TexText][INFO    ]:       |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gtk3[0m
    [TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
    [TexText][ERROR   ]: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
    	/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture
    	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture (1)
    [TexText][ERROR   ]: Traceback (most recent call last):
      File "/Users/username/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/__main__.py", line 8, in <module>
        effect.run()
      File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 140, in run
        self.save_raw(self.effect())
      File "/Users/username/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/base.py", line 212, in effect
        from .asktext import AskTextDefault
      File "/Users/username/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/asktext.py", line 59, in <module>
        from gi.repository import Gtk
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
        importlib.import_module('gi.repository.' + dep.split("-")[0])
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
        importlib.import_module('gi.repository.' + dep.split("-")[0])
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
        importlib.import_module('gi.repository.' + dep.split("-")[0])
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
        importlib.import_module('gi.repository.' + dep.split("-")[0])
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
      File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
        dynamic_module = load_overrides(introspection_module)
      File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
        override_mod = importlib.import_module(override_package_name)
      File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/GLib.py", line 37, in <module>
        from gi import _option as option
      File "/opt/homebrew/lib/python3.9/site-packages/gi/_option.py", line 40, in <module>
        OPTION_CONTEXT_ERROR_QUARK = GLib.quark_to_string(GLib.option_error_quark())
    gi._error.GError: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
    	/Applications/Inkscape.app/Contents/MacOS/../Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture
    	/Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib: mach-o, but wrong architecture (1)    

    [TexText][INFO    ]: TexText finished with error, please run extension again
    [TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md

And it seems to point to the mixed lib paths...i am quite sure that in my lib path (`/opt/homebrew/lib`) I have the correct libs, but inkscape is searching them in `/Applications/Inkscape.app/Contents/MacOS/../Resources/` and `/Applications/Inkscape.app/Contents/Resources/lib/`
