### ISSUE TITLE
Textext 1.5 fails in Inkscape 1.1 on MAC OS 10.15.7

### ISSUE THREAD

**Issue by yoramzarai** [textext/textext#318]
**Before submitting a bug report make sure you have checked the
  [FAQ](https://textext.github.io/textext/usage/faq.html) and
  [Troubleshooting](https://textext.github.io/textext/usage/troubleshooting.html)
  sections in the documentation!**

**Description of the problem/ steps to reproduce**
Run Inkspace version 1.1. Execute Extension->Text-> Tex Text. Then a window opens with the Traceback text that appears below. Then clicking ```OK``` in that window closes the window and we are back at the Inkscape main window. 

**Steps to reproduce the behavior (if not obvious from description)**:
1. ....
2. ....
3. ....

**Message(s) in error dialog (if this comes up)**
Please paste the error message(s) at the marked positions:

<details>
<summary>dialog output (if available):</summary>

```
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
    from textext.base import *
  File "/Users/yoramzarai/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/base.py", line 105, in <module>
    import inkex
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 15, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 33, in <module>
    from .elements import load_svg, BaseElement, ShapeElement, Group, Layer, Grid, \
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 9, in <module>
    from ._base import SVG_PARSER, load_svg, ShapeElement, BaseElement
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module>
    from lxml import etree
ImportError: dlopen(/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so: code signature in (/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```
</details>

<details>
<summary>output of stdout (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

<details>
<summary>output of stderr (if available):</summary>

```
<<< REPLACE THIS LINE WITH ACTUAL OUTPUT >>> 
```
</details>

**Logfile**
Please also *attach* the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows

[textext.log](https://github.com/textext/textext/files/7195863/textext.log)

**Screenshots**
If applicable and helpful, add screenshots to help explain your problem.

**System information**

- TexText version: 1.5
- Inkscape version: 1.1
- Operating system: [e.g. Windows 10, 1803, 32-bit] MAC OS 10.15.7
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live):
- Windows only: TexText installed via batch script or installer file:

**Additional information if you still use Inkscape 0.92.x / TexText 0.11**

- SVG-converter installed (pstoedit+ghostscript or pdf2svg):
- GUI framework installed (PyGTK, PyGTK+PyGTK-Sourceview, TkInter):

**Comment by jcwinkler** [comment]
Thanks for the report. According to the information you provided I have the following question:

The log file output states that Inkscape 1.0.1 has been used for compilation of a LaTeX snippet. This indicates, that the log file has been created by a working TexText installation. I guess you used Inkscape 1.0.1 so far and then upgraded to 1.1 and now TexText does not launch?

Anyway, the dialog output tells us that the Python distrubution shipped with Inkscape on MacOS or to which Inkscape is connected on MacOS seems to be broken (`from lxml import etree` is an import done by the Inkscape extension system, not by TexText).

**Comment by yoramzarai** [comment]
Thanks for the reply.

Yes - I have both Inkscape 1.0.1 (4035a4f, 2020-05-01) and 1.1 installed on my MAC. I also have both Tex Text 1.1.0 and 1.5.0 in the extensions folder. Inkscape 1.0.1 works with both Tex Text 1.1.0 and 1.5.0. However, Inkscape 1.1 fails with both Tex Text versions yielding the same error message.

**Comment by jcwinkler** [comment]
@yoramzarai Is the so called "extension manager" available in Inkscape 1.1 on your MAC (at the bottom of the extension menu)? Does it launch? Do other extensions work (e.g. Render - Mathematics - pdflatex)?

**Comment by yoramzarai** [comment]
Upon clicking on ```Extensions - Manage Extension``` I get the same error:
```
Traceback (most recent call last):
  File "extension-manager-bootstrap.py", line 28, in <module>
    import inkex
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 15, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 33, in <module>
    from .elements import load_svg, BaseElement, ShapeElement, Group, Layer, Grid, \
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 9, in <module>
    from ._base import SVG_PARSER, load_svg, ShapeElement, BaseElement
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module>
    from lxml import etree
ImportError: dlopen(/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so: code signature in (/Users/yoramzarai/Library/Python/3.8/lib/python/site-packages/lxml/etree.cpython-38-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```


As for ```Render - Mathematics```, the LaTex (pdflatex) is grayed out.

**Comment by jcwinkler** [comment]
OK, then we should file a bug report in the [Inkscape extension repo](https://gitlab.com/inkscape/extensions/-/issues) relating the `Extensions - Manage Extension` issue. When that being fixed we can continue to find the error invoking TexText.

**Comment by yoramzarai** [comment]
The issue was the python interpreter. It was solved as specified [here](https://gitlab.com/inkscape/extensions/-/issues/414). Now Tex Text works.

**Comment by jcwinkler** [comment]
@yoramzarai Is there something I could add to the installation instructions which might help other users?

**Comment by yoramzarai** [comment]
I think this is more an Inkscape extensions issue and not specific to TexText. [This](https://wiki.inkscape.org/wiki/Extension_Interpreters) was useful for me to resolve the problem, but, again, this is not specific for TexText extension.
