### ISSUE TITLE
Error running TexText on macOS

### ISSUE THREAD

**Issue by omrilesser** [textext/textext#343]
Hi,

I'm trying to run TexText 1.7.1 on Inkscape 1.1. My machine is an M1 MacBook Air (2020 model) running macOS Monterey 12.0.1.
I installed Inkscape via homebrew, and also the python3 interpreter via homebrew (as described in the docs). When I try to start TexText, I get an error message:

<details>
<summary>Error mesaage:</summary>

```

** (process:63615): WARNING **: 11:37:05.671: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 0x0009): tried: '/Applications/Inkscape.app/Contents/Resources/lib/libpango-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpango-1.0.0.dylib' (no such file), '/opt/homebrew/lib/libpango-1.0.0.dylib' (no such file), 'libpango-1.0.0.dylib' (no such file), '/usr/local/lib/libpango-1.0.0.dylib' (no such file), '/usr/lib/libpango-1.0.0.dylib' (no such file), '/Applications/Inkscape.app/Contents/Resources/lib/libpango-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpango-1.0.0.dylib' (no such file), '/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/libpango-1.0.0.dylib' (no such file), '/usr/local/lib/libpango-1.0.0.dylib' (no such file), '/usr/lib/libpango-1.0.0.dylib' (no such file)
[TexText][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '1.7.1' (md5sum = b9c1dc49dd6ce9401e865b5c8490831e)
[TexText][DEBUG   ]: platform.system() = 'Darwin'
[TexText][DEBUG   ]: platform.release() = '21.1.0'
[TexText][DEBUG   ]: platform.version() = 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101'
[TexText][DEBUG   ]: platform.machine() = 'arm64'
[TexText][DEBUG   ]: platform.uname() = uname_result(system='Darwin', node="omrile's-MacBook-Air", release='21.1.0', version='Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101', machine='arm64')
[TexText][DEBUG   ]: platform.mac_ver() = ('12.0.1', ('', '', ''), 'arm64')
[TexText][DEBUG   ]: sys.executable = '/opt/homebrew/opt/python@3.9/bin/python3.9'
[TexText][DEBUG   ]: sys.version = '3.9.10 (main, Jan 15 2022, 11:40:53) \n[Clang 13.0.0 (clang-1300.0.29.3)]'
[TexText][DEBUG   ]: os.environ = environ({'USER': 'omrile', '__CFBundleIdentifier': 'org.inkscape.Inkscape', 'COMMAND_MODE': 'unix2003', 'LOGNAME': 'omrile', 'PATH': '/Applications/Inkscape.app/Contents/MacOS:/Applications/Inkscape.app/Contents/Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.TCTjOyWvFm/Listeners', 'SHELL': '/bin/zsh', 'HOME': '/Users/omrile', '__CF_USER_TEXT_ENCODING': '0x1F6:0x0:0x0', 'TMPDIR': '/var/folders/xw/hk_llrcn177f6zj6r8f7c9_m0000gp/T/', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'XDG_DATA_HOME': '/Users/omrile/Library/Application Support/org.inkscape.Inkscape/share', 'XDG_DATA_DIRS': '/Applications/Inkscape.app/Contents/Resources/share:/Applications/Inkscape.app/Contents/Resources/share/inkscape', 'XDG_CONFIG_HOME': '/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config', 'XDG_CONFIG_DIRS': '/Applications/Inkscape.app/Contents/Resources/etc/xdg', 'XDG_CACHE_HOME': '/Users/omrile/Library/Application Support/org.inkscape.Inkscape/cache', 'GTK_EXE_PREFIX': '/Applications/Inkscape.app/Contents/Resources', 'GTK_DATA_PREFIX': '/Applications/Inkscape.app/Contents/Resources', 'GDK_PIXBUF_MODULE_FILE': '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache', 'FONTCONFIG_PATH': '/Applications/Inkscape.app/Contents/Resources/etc/fonts', 'GIO_MODULE_DIR': '/Applications/Inkscape.app/Contents/Resources/lib/gio/modules', 'GI_TYPELIB_PATH': '/Applications/Inkscape.app/Contents/Resources/lib/girepository-1.0', 'DYLD_LIBRARY_PATH': '/Applications/Inkscape.app/Contents/Resources/lib:/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders', 'PYTHONPATH': '/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions:/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/deprecated-simple', 'PYTHONIOENCODING': 'UTF-8', 'INKSCAPE_PROFILE_DIR': '/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config/inkscape', 'DOCUMENT_PATH': '', '__KMP_REGISTERED_LIB_63538': '0x1126cb268-cafebaaf-libomp.dylib', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKEX_GETTEXT_DIRECTORY': '/Applications/Inkscape.app/Contents/Resources/share/locale', 'LC_CTYPE': 'UTF-8'})
[TexText][INFO    ]: Using `pdflatex-executable` = `/Library/TeX/texbin/pdflatex`
[TexText][INFO    ]: Using `lualatex-executable` = `/Library/TeX/texbin/lualatex`
[TexText][INFO    ]: Using `xelatex-executable` = `/Library/TeX/texbin/xelatex`
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/Library/TeX/texbin/pdflatex`
[TexText][SUCCESS ]: |     /--or-* [Succ] lualatex is found at `/Library/TeX/texbin/lualatex`
[TexText][SUCCESS ]: |     /--or-* [Succ] xelatex is found at `/Library/TeX/texbin/xelatex`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][INFO    ]:       /--or-* [Fail] GTK3 is not found
[TexText][INFO    ]:       |      Please follow installation instructions at 
[TexText][INFO    ]:       |             [94m[4mhttps://textext.github.io/textext/install/macos.html#macos-install-gtk3[0m
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][ERROR   ]: 
[TexText][ERROR   ]: Traceback (most recent call last):
  File "/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/__main__.py", line 24, in <module>
    effect.run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/base.py", line 182, in effect
    from .asktext import AskTextDefault
  File "/Users/omrile/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/textext/asktext.py", line 62, in <module>
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md
```
</details>

logfile attached:
[textext.log](https://github.com/textext/textext/files/8039833/textext.log)

Thanks!

**Comment by omrilesser** [comment]
Hi @jcwinkler ,
I did perform all the steps, but apparently the symlink at the homebrew folder did not link to the correct place. So following your advice I ran `brew doctor` and apparently the python 3.9 interpreter is at `~/opt/anaconda3/bin/python3.9` (maybe that is because I have anaconda installed). I changed that in `preferences.xml` and now it works perfectly!
Thanks a lot!
