### ISSUE TITLE
Error with TeXText Extension

### ISSUE THREAD

**Issue by annaschenfisch** [textext/textext#359]
**Before submitting a bug report make sure you have checked the
  [FAQ](https://textext.github.io/textext/usage/faq.html) and
  [Troubleshooting](https://textext.github.io/textext/usage/troubleshooting.html)
  sections in the documentation!**

**Description of the problem/ steps to reproduce**
After installing a newer version of inkscape and installing textext, I encountered this error. I attempted uninstalling and reinstalling textext, but encountered the same error.

**Message(s) in error dialog (if this comes up)**

<details>
<summary>dialog output (if available):</summary>

[TexText][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.
[TexText][DEBUG   ]: TexText initialized
[TexText][DEBUG   ]: TexText version = '1.8.1' (md5sum = 7df5f3e0b71fd7ead8f25644e78db9de)
[TexText][DEBUG   ]: platform.system() = 'Windows'
[TexText][DEBUG   ]: platform.release() = '10'
[TexText][DEBUG   ]: platform.version() = '10.0.19044'
[TexText][DEBUG   ]: platform.machine() = 'AMD64'
[TexText][DEBUG   ]: platform.uname() = uname_result(system='Windows', node='LAPTOP-1HO54C1C', release='10', version='10.0.19044', machine='AMD64')
[TexText][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')
[TexText][DEBUG   ]: sys.executable = 'C:\\Program Files (x86)\\Inkscape\\bin\\pythonw.exe'
[TexText][DEBUG   ]: sys.version = '3.9.10 (main, Jan 25 2022, 17:57:21)  [GCC 11.2.0 32 bit]'
[TexText][DEBUG   ]: os.environ = environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'LAPTOP-1HO54C1C', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DOCUMENT_PATH': '', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Anna Schenfisch', 'INKEX_GETTEXT_DIRECTORY': 'C:\\Program Files (x86)\\Inkscape\\share/locale', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKSCAPE_PROFILE_DIR': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming\\inkscape', 'LOCALAPPDATA': 'C:\\Users\\Anna Schenfisch\\AppData\\Local', 'LOGONSERVER': '\\\\LAPTOP-1HO54C1C', 'NUMBER_OF_PROCESSORS': '4', 'ONEDRIVE': 'C:\\Users\\Anna Schenfisch\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Anna Schenfisch\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Program Files (x86)\\Inkscape\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\MATLAB\\R2019b\\bin;C:\\Program Files\\Wolfram Research\\WolframScript\\;C:\\Program Files\\gs\\gs9.56.1\\bin;C:\\Program Files (x86)\\Inkscape\\bin;C:\\Users\\Anna Schenfisch\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Anna Schenfisch\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;;C:\\Program Files (x86)\\Inkscape\\bin\\', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'x86', 'PROCESSOR_ARCHITEW6432': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e09', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files (x86)', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '$P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming\\inkscape\\extensions;C:\\Program Files (x86)\\Inkscape\\share\\inkscape\\extensions;C:\\Program Files (x86)\\Inkscape\\share\\inkscape\\extensions\\inkex\\deprecated-simple', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ANNASC~1\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ANNASC~1\\AppData\\Local\\Temp', 'USERDOMAIN': 'LAPTOP-1HO54C1C', 'USERDOMAIN_ROAMINGPROFILE': 'LAPTOP-1HO54C1C', 'USERNAME': 'Anna Schenfisch', 'USERPROFILE': 'C:\\Users\\Anna Schenfisch', 'WINDIR': 'C:\\WINDOWS', 'XDG_DATA_DIRS': 'C:\\ProgramData;C:\\Users\\Public\\Documents;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share\\inkscape'})
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0
[TexText][SUCCESS ]: |      inkscape=1.1 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
[TexText][DEBUG   ]: TexText.effect
[TexText][DEBUG   ]:   Using default preamble file `default_packages.tex`
[TexText][DEBUG   ]:   Run TexText GUI
[TexText][DEBUG   ]:   Run TexText GUI failed
[TexText][DEBUG   ]: TexText.effect failed
[TexText][ERROR   ]: could not get a reference to type class
[TexText][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 24, in <module>
    effect.run()
  File "C:\Program Files (x86)\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\base.py", line 274, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1270, in ask
    window = self.create_window()
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1106, in create_window
    text_buffer = GtkSource.Buffer()
TypeError: could not get a reference to type class

[TexText][INFO    ]: TexText finished with error, please run extension again
[TexText][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md
</details>

<details>
<summary>logfile:</summary>

**Logfile**
[2022-07-18 12:03:00,362][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.          //  base.py:103  
[2022-07-18 12:03:00,363][DEBUG   ]: TexText initialized          //  base.py:112  
[2022-07-18 12:03:00,364][DEBUG   ]: TexText version = '1.8.1' (md5sum = 7df5f3e0b71fd7ead8f25644e78db9de)          //  base.py:114  
[2022-07-18 12:03:00,365][DEBUG   ]: platform.system() = 'Windows'          //  base.py:117  
[2022-07-18 12:03:00,365][DEBUG   ]: platform.release() = '10'          //  base.py:118  
[2022-07-18 12:03:00,366][DEBUG   ]: platform.version() = '10.0.19044'          //  base.py:119  
[2022-07-18 12:03:00,366][DEBUG   ]: platform.machine() = 'AMD64'          //  base.py:121  
[2022-07-18 12:03:00,366][DEBUG   ]: platform.uname() = uname_result(system='Windows', node='LAPTOP-1HO54C1C', release='10', version='10.0.19044', machine='AMD64')          //  base.py:122  
[2022-07-18 12:03:00,368][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')          //  base.py:123  
[2022-07-18 12:03:00,368][DEBUG   ]: sys.executable = 'C:\\Program Files (x86)\\Inkscape\\bin\\pythonw.exe'          //  base.py:125  
[2022-07-18 12:03:00,369][DEBUG   ]: sys.version = '3.9.10 (main, Jan 25 2022, 17:57:21)  [GCC 11.2.0 32 bit]'          //  base.py:126  
[2022-07-18 12:03:00,371][DEBUG   ]: os.environ = environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'LAPTOP-1HO54C1C', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DOCUMENT_PATH': '', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Anna Schenfisch', 'INKEX_GETTEXT_DIRECTORY': 'C:\\Program Files (x86)\\Inkscape\\share/locale', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKSCAPE_PROFILE_DIR': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming\\inkscape', 'LOCALAPPDATA': 'C:\\Users\\Anna Schenfisch\\AppData\\Local', 'LOGONSERVER': '\\\\LAPTOP-1HO54C1C', 'NUMBER_OF_PROCESSORS': '4', 'ONEDRIVE': 'C:\\Users\\Anna Schenfisch\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Anna Schenfisch\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Program Files (x86)\\Inkscape\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\MATLAB\\R2019b\\bin;C:\\Program Files\\Wolfram Research\\WolframScript\\;C:\\Program Files\\gs\\gs9.56.1\\bin;C:\\Program Files (x86)\\Inkscape\\bin;C:\\Users\\Anna Schenfisch\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Anna Schenfisch\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;;C:\\Program Files (x86)\\Inkscape\\bin\\', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'x86', 'PROCESSOR_ARCHITEW6432': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e09', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files (x86)', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '$P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming\\inkscape\\extensions;C:\\Program Files (x86)\\Inkscape\\share\\inkscape\\extensions;C:\\Program Files (x86)\\Inkscape\\share\\inkscape\\extensions\\inkex\\deprecated-simple', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ANNASC~1\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ANNASC~1\\AppData\\Local\\Temp', 'USERDOMAIN': 'LAPTOP-1HO54C1C', 'USERDOMAIN_ROAMINGPROFILE': 'LAPTOP-1HO54C1C', 'USERNAME': 'Anna Schenfisch', 'USERPROFILE': 'C:\\Users\\Anna Schenfisch', 'WINDIR': 'C:\\WINDOWS', 'XDG_DATA_DIRS': 'C:\\ProgramData;C:\\Users\\Public\\Documents;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share\\inkscape'})          //  base.py:127  
[2022-07-18 12:03:01,874][SUCCESS ]: + [Succ] TexText requirements          //  requirements_check.py:747  
[2022-07-18 12:03:01,874][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0          //  requirements_check.py:388  
[2022-07-18 12:03:01,875][SUCCESS ]: |      inkscape=1.1 is found          //  requirements_check.py:388  
[2022-07-18 12:03:01,876][SUCCESS ]: /-and-+ [Succ] Detect *latex          //  requirements_check.py:388  
[2022-07-18 12:03:01,878][SUCCESS ]: |     /--or-* [Succ] `pdflatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`          //  requirements_check.py:388  
[2022-07-18 12:03:01,880][SUCCESS ]: |     /--or-* [Succ] `lualatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`          //  requirements_check.py:388  
[2022-07-18 12:03:01,881][SUCCESS ]: |     /--or-* [Succ] `xelatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`          //  requirements_check.py:388  
[2022-07-18 12:03:01,881][SUCCESS ]: /-and-+ [Succ] Detect GUI library          //  requirements_check.py:388  
[2022-07-18 12:03:01,882][SUCCESS ]:       /--or-* [Succ] GTK3 is found          //  requirements_check.py:388  
[2022-07-18 12:03:01,882][SUCCESS ]:       /--or-* [Succ] TkInter is found          //  requirements_check.py:388  
[2022-07-18 12:03:02,359][DEBUG   ]: TexText.effect          //  base.py:184  
[2022-07-18 12:03:02,360][DEBUG   ]:   Using default preamble file `default_packages.tex`          //  base.py:228  
[2022-07-18 12:03:02,361][DEBUG   ]:   Run TexText GUI          //  base.py:273  
[2022-07-18 12:03:04,327][DEBUG   ]:   Run TexText GUI failed          //  base.py:274  
[2022-07-18 12:03:04,328][DEBUG   ]: TexText.effect failed          //  base.py:287  
[2022-07-18 12:03:04,330][ERROR   ]: could not get a reference to type class          //  __main__.py:57   
[2022-07-18 12:03:04,333][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 24, in <module>
    effect.run()
  File "C:\Program Files (x86)\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\base.py", line 274, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1270, in ask
    window = self.create_window()
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1106, in create_window
    text_buffer = GtkSource.Buffer()
TypeError: could not get a reference to type class
          //  __main__.py:58   
[2022-07-18 12:03:04,334][INFO    ]: TexText finished with error, please run extension again          //  __main__.py:59   
[2022-07-18 12:03:04,334][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md          //  __main__.py:60   
[2022-07-18 12:03:56,139][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.          //  base.py:103  
[2022-07-18 12:03:56,140][DEBUG   ]: TexText initialized          //  base.py:112  
[2022-07-18 12:03:56,141][DEBUG   ]: TexText version = '1.8.1' (md5sum = 7df5f3e0b71fd7ead8f25644e78db9de)          //  base.py:114  
[2022-07-18 12:03:56,142][DEBUG   ]: platform.system() = 'Windows'          //  base.py:117  
[2022-07-18 12:03:56,143][DEBUG   ]: platform.release() = '10'          //  base.py:118  
[2022-07-18 12:03:56,143][DEBUG   ]: platform.version() = '10.0.19044'          //  base.py:119  
[2022-07-18 12:03:56,143][DEBUG   ]: platform.machine() = 'AMD64'          //  base.py:121  
[2022-07-18 12:03:56,144][DEBUG   ]: platform.uname() = uname_result(system='Windows', node='LAPTOP-1HO54C1C', release='10', version='10.0.19044', machine='AMD64')          //  base.py:122  
[2022-07-18 12:03:56,144][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')          //  base.py:123  
[2022-07-18 12:03:56,145][DEBUG   ]: sys.executable = 'C:\\Program Files (x86)\\Inkscape\\bin\\pythonw.exe'          //  base.py:125  
[2022-07-18 12:03:56,145][DEBUG   ]: sys.version = '3.9.10 (main, Jan 25 2022, 17:57:21)  [GCC 11.2.0 32 bit]'          //  base.py:126  
[2022-07-18 12:03:56,149][DEBUG   ]: os.environ = environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'LAPTOP-1HO54C1C', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DOCUMENT_PATH': '', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Anna Schenfisch', 'INKEX_GETTEXT_DIRECTORY': 'C:\\Program Files (x86)\\Inkscape\\share/locale', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKSCAPE_PROFILE_DIR': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming\\inkscape', 'LOCALAPPDATA': 'C:\\Users\\Anna Schenfisch\\AppData\\Local', 'LOGONSERVER': '\\\\LAPTOP-1HO54C1C', 'NUMBER_OF_PROCESSORS': '4', 'ONEDRIVE': 'C:\\Users\\Anna Schenfisch\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Anna Schenfisch\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Program Files (x86)\\Inkscape\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\MATLAB\\R2019b\\bin;C:\\Program Files\\Wolfram Research\\WolframScript\\;C:\\Program Files\\gs\\gs9.56.1\\bin;C:\\Program Files (x86)\\Inkscape\\bin;C:\\Users\\Anna Schenfisch\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Anna Schenfisch\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;;C:\\Program Files (x86)\\Inkscape\\bin\\', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'x86', 'PROCESSOR_ARCHITEW6432': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e09', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files (x86)', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '$P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'C:\\Users\\Anna Schenfisch\\AppData\\Roaming\\inkscape\\extensions;C:\\Program Files (x86)\\Inkscape\\share\\inkscape\\extensions;C:\\Program Files (x86)\\Inkscape\\share\\inkscape\\extensions\\inkex\\deprecated-simple', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ANNASC~1\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ANNASC~1\\AppData\\Local\\Temp', 'USERDOMAIN': 'LAPTOP-1HO54C1C', 'USERDOMAIN_ROAMINGPROFILE': 'LAPTOP-1HO54C1C', 'USERNAME': 'Anna Schenfisch', 'USERPROFILE': 'C:\\Users\\Anna Schenfisch', 'WINDIR': 'C:\\WINDOWS', 'XDG_DATA_DIRS': 'C:\\ProgramData;C:\\Users\\Public\\Documents;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share;C:\\Program Files (x86)\\Inkscape\\share\\inkscape'})          //  base.py:127  
[2022-07-18 12:03:57,486][SUCCESS ]: + [Succ] TexText requirements          //  requirements_check.py:747  
[2022-07-18 12:03:57,487][SUCCESS ]: /-and-* [Succ] Detect inkscape>=1.0          //  requirements_check.py:388  
[2022-07-18 12:03:57,487][SUCCESS ]: |      inkscape=1.1 is found          //  requirements_check.py:388  
[2022-07-18 12:03:57,488][SUCCESS ]: /-and-+ [Succ] Detect *latex          //  requirements_check.py:388  
[2022-07-18 12:03:57,488][SUCCESS ]: |     /--or-* [Succ] `pdflatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`          //  requirements_check.py:388  
[2022-07-18 12:03:57,489][SUCCESS ]: |     /--or-* [Succ] `lualatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`          //  requirements_check.py:388  
[2022-07-18 12:03:57,490][SUCCESS ]: |     /--or-* [Succ] `xelatex.exe` is found at `C:\Users\Anna Schenfisch\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\`          //  requirements_check.py:388  
[2022-07-18 12:03:57,490][SUCCESS ]: /-and-+ [Succ] Detect GUI library          //  requirements_check.py:388  
[2022-07-18 12:03:57,491][SUCCESS ]:       /--or-* [Succ] GTK3 is found          //  requirements_check.py:388  
[2022-07-18 12:03:57,491][SUCCESS ]:       /--or-* [Succ] TkInter is found          //  requirements_check.py:388  
[2022-07-18 12:03:57,754][DEBUG   ]: TexText.effect          //  base.py:184  
[2022-07-18 12:03:57,755][DEBUG   ]:   Using default preamble file `default_packages.tex`          //  base.py:228  
[2022-07-18 12:03:57,756][DEBUG   ]:   Run TexText GUI          //  base.py:273  
[2022-07-18 12:03:58,925][DEBUG   ]:   Run TexText GUI failed          //  base.py:274  
[2022-07-18 12:03:58,926][DEBUG   ]: TexText.effect failed          //  base.py:287  
[2022-07-18 12:03:58,926][ERROR   ]: could not get a reference to type class          //  __main__.py:57   
[2022-07-18 12:03:58,929][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 24, in <module>
    effect.run()
  File "C:\Program Files (x86)\Inkscape\share\inkscape\extensions\inkex\base.py", line 131, in run
    self.save_raw(self.effect())
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\base.py", line 274, in effect
    gui_config = asker.ask(save_callback, preview_callback)
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1270, in ask
    window = self.create_window()
  File "C:\Users\Anna Schenfisch\AppData\Roaming\inkscape\extensions\textext\asktext.py", line 1106, in create_window
    text_buffer = GtkSource.Buffer()
TypeError: could not get a reference to type class
          //  __main__.py:58   
[2022-07-18 12:03:58,930][INFO    ]: TexText finished with error, please run extension again          //  __main__.py:59   
[2022-07-18 12:03:58,931][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md          //  __main__.py:60   

</details>

**Screenshots**
N/A

**System information**

- TexText version: 1.8.1
- Inkscape version: 1.1.2
- Operating system: Windows 10, 64-bit
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTeX
- Windows only: TexText installed via batch script or installer file: installer

**Comment by jcwinkler** [comment]
@annaschenfisch The error message indicates that something is wrong with GtkSourceView, the component of the Inkscape extension system responsible to do the syntax highlighting in TexText. I suggest to do the following:

1. Uninstall Inkscape (this will not delete any personal Inkscape settings)
2. Uninstall GtkSourceview:
   a. Open the Windwos Control Panel
   b. Select Programs > Programs and Features
   c. Search for "PyGTKSourceView for Inkscape" or "GtkSourceView for Inkscape", or similar
   d. Uninstall it
3. Check if the Inkscape installation folder (usually C:\Program Files\Inkscape) is completely removed. If not, manually remove it. (this again will not delete any personal Inkscape settings)
4. Re-install Inkscape.

I guess your already installed TexText should run again. If so, we can re-setup GtkSourceView (for syntax highlighting). If not, we have to look for another solution.
