### ISSUE TITLE
textext refuses to open

### ISSUE THREAD

**Issue by luciandf** [textext/textext#404]
**Description of the problem/ steps to reproduce**
I select textext from the extensions menu and it doesn't open. I have inkscape 1.3 installed and I used the windows installer for textext 1.9 to install the extension. I have checked it is in the right place in windows 11.

There is no error message no nothing. Just doesn't run. I tried restarting the computer, reinstalled inkscape but nothing.

What is there that I can do to make it run?

**Comment by jcwinkler** [comment]
Is there a log file available at `c:\Users\[your username]\AppData\Roaming\textext`? If so, delete it and try to re-run textext again. Then check the log file for errors or post it.

**Comment by luciandf** [comment]
found it and did what you said. here is the log:

````
[2023-11-17 12:02:41,694][ERROR   ]: Bad config `C:\Users\Lucian\AppData\Roaming\textext\config.json`: Expecting value: line 1 column 1 (char 0). Please fix it and re-run TexText.          //  __main__.py:45   
[2023-11-17 12:03:30,073][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.          //  base.py:104  
[2023-11-17 12:03:30,073][DEBUG   ]: TexText initialized          //  base.py:113  
[2023-11-17 12:03:30,082][DEBUG   ]: TexText version = '1.9.0' (md5sum = 95ab71910d4376a454f01245ef595d9f)          //  base.py:115  
[2023-11-17 12:03:30,082][DEBUG   ]: platform.system() = 'Windows'          //  base.py:118  
[2023-11-17 12:03:30,083][DEBUG   ]: platform.release() = '10'          //  base.py:119  
[2023-11-17 12:03:30,083][DEBUG   ]: platform.version() = '10.0.22631'          //  base.py:120  
[2023-11-17 12:03:30,083][DEBUG   ]: platform.machine() = 'AMD64'          //  base.py:122  
[2023-11-17 12:03:30,083][DEBUG   ]: platform.uname() = uname_result(system='Windows', node='thor', release='10', version='10.0.22631', machine='AMD64')          //  base.py:123  
[2023-11-17 12:03:30,083][DEBUG   ]: platform.mac_ver() = ('', ('', '', ''), '')          //  base.py:124  
[2023-11-17 12:03:30,084][DEBUG   ]: sys.executable = 'C:\\Program Files\\Inkscape\\bin\\pythonw.exe'          //  base.py:126  
[2023-11-17 12:03:30,084][DEBUG   ]: sys.version = '3.10.12 (main, Jun 14 2023, 19:14:29)  [GCC 13.1.0 64 bit (AMD64)]'          //  base.py:127  
[2023-11-17 12:03:30,084][DEBUG   ]: os.environ = environ({'ACSETUPSVCPORT': '23210', 'ACSVCPORT': '17532', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Lucian\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'THOR', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'DOCUMENT_PATH': '', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'EFC_10664': '1', 'GDK_WIN32_USE_EXPERIMENTAL_OLE2_DND': '1', 'HOME': 'C:\\Users\\Lucian', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Lucian', 'INKEX_GETTEXT_DIRECTORY': 'C:\\Program Files\\Inkscape\\share/locale', 'INKEX_GETTEXT_DOMAIN': 'inkscape', 'INKSCAPE_PROFILE_DIR': 'C:\\Users\\Lucian\\AppData\\Roaming\\inkscape', 'LOCALAPPDATA': 'C:\\Users\\Lucian\\AppData\\Local', 'LOGONSERVER': '\\\\THOR', 'MOZ_PLUGIN_PATH': 'C:\\Program Files (x86)\\Foxit Software\\Foxit PDF Reader\\plugins\\', 'NUMBER_OF_PROCESSORS': '16', 'ONEDRIVE': 'C:\\Users\\Lucian\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Lucian\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Program Files\\Inkscape\\bin;C:\\Program Files\\Inkscape\\bin\\;C:\\Program Files\\Python312\\Scripts\\;C:\\Program Files\\Python312\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\gs\\gs10.00.0\\bin;C:\\Program Files\\WireGuard\\;C:\\Program Files\\Wolfram Research\\WolframScript\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\dotnet\\;C:\\Program Files\\Calibre2\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\PuTTY\\;C:\\Program Files\\FileBot\\;C:\\Users\\Lucian\\AppData\\Local\\Microsoft\\WindowsApps;C:\\texlive\\2023\\bin\\windows;C:\\Program Files\\Inkscape\\bin\\', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD', 'PROCESSOR_LEVEL': '25', 'PROCESSOR_REVISION': '4401', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'C:\\Users\\Lucian\\AppData\\Roaming\\inkscape\\extensions;C:\\Program Files\\Inkscape\\share\\inkscape\\extensions;C:\\Program Files\\Inkscape\\share\\inkscape\\extensions\\inkex\\deprecated-simple', 'RLSSVCPORT': '22112', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\Lucian\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\Lucian\\AppData\\Local\\Temp', 'USERDOMAIN': 'THOR', 'USERDOMAIN_ROAMINGPROFILE': 'THOR', 'USERNAME': 'Lucian', 'USERPROFILE': 'C:\\Users\\Lucian', 'WINDIR': 'C:\\Windows', 'XDG_DATA_DIRS': 'C:\\ProgramData;C:\\Users\\Public\\Documents;C:\\Program Files\\Inkscape\\share;C:\\Program Files\\Inkscape\\share;C:\\Program Files\\Inkscape\\share;C:\\Program Files\\Inkscape\\share\\inkscape'})          //  base.py:128  
[2023-11-17 12:03:30,163][ERROR   ]: 'int' object has no attribute 'get'          //  __main__.py:57   
[2023-11-17 12:03:30,180][ERROR   ]: Traceback (most recent call last):
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\__main__.py", line 23, in <module>
    effect = TexText()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\base.py", line 140, in __init__
    if self.requirements_checker.check() == False:
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 758, in check
    check_result = textext_requirements.check()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 531, in and_impl
    L = self.check()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 532, in and_impl
    R = rhs.check()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 544, in or_impl
    L = self.check()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 544, in or_impl
    L = self.check()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 480, in check
    result = self.criteria()
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 470, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\requirements_check.py", line 659, in find_executable
    executable_path = self.config.get(prog_name+"-executable", None)
  File "C:\Users\Lucian\AppData\Roaming\inkscape\extensions\textext\utility.py", line 188, in get
    result = self.values.get(key, default)
AttributeError: 'int' object has no attribute 'get'
          //  __main__.py:58   
[2023-11-17 12:03:30,180][INFO    ]: TexText finished with error, please run extension again          //  __main__.py:59   
[2023-11-17 12:03:30,181][INFO    ]: If problem persists, please file a bug https://github.com/textext/textext/issues/new?template=bug_report.md          //  __main__.py:60
