### ISSUE TITLE
GTK Not Working MacOS

### ISSUE THREAD

**Issue by nraikm** [textext/textext#426]
**Description of the problem/ steps to reproduce**
I have set Inkscape (installed using Homebrew) to use a new Python interpreter (either 3.10 or 3.9, installed by homebrew), installed the packages as mentioned in the MacOS documentation, and am not able to load the GTK version of TexText (nor the Manage Extensions popup either). By using the default interpreter, everything works fine (including the GTK version of TexText) except the windows are not opened in focus (click on the menu item and have to click on another app—shown as "Python" in the MacOS toolbar to open the window, or move the Inkscape window to see the new window beneath it). This is why I chose to try to set this up with a new interpreter, which does open up the windows in focus (at least the Tkinter version of TexText).

The setup script mentions that GTK is installed (did pip3 install PyGObject):
```
[TexText][INFO    ]: Using `pdflatex-executable` = `/Library/TeX/texbin/pdflatex`
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape >= 1.3
[TexText][SUCCESS ]: |      inkscape=1.3 is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] pdflatex is found at `/Library/TeX/texbin/pdflatex`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex` is found at `/Library/TeX/texbin`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex` is found at `/Library/TeX/texbin`
[TexText][INFO    ]: |     /--or-* [Fail] `typst` is NOT found in PATH
[TexText][INFO    ]: |            Please follow installation instructions at 
[TexText][INFO    ]: |                   https://textext.github.io/textext/install/macos.html#macos-install-preparation
[TexText][INFO    ]: |            If typst is installed in custom location, specify it via 
[TexText][INFO    ]: |                   --typst-executable=<path-to-typst>
[TexText][INFO    ]: |            and run setup.py again
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]:       /--or-* [Succ] GTK3 is found
[TexText][SUCCESS ]:       /--or-* [Succ] TkInter is found
```

I have also set the Python interpreter in Inkscape to point to the proper directory:
```
<group
     id="extensions"
     org.inkscape.output.png.inkscape.png_bitdepth="99"
     org.inkscape.output.png.inkscape.png_compression="6"
     org.inkscape.output.png.inkscape.png_antialias="2"
     python-interpreter="/opt/homebrew/opt/python@3.10/libexec/bin/python3" />
```

However, when I open the TexText dialogue, it shows me the older Tkinter GUI. 
<img width="556" alt="Screenshot 2024-03-30 at 2 56 55 PM" src="https://github.com/textext/textext/assets/18247709/4f732983-3b2a-4e57-a4b0-4b96c944a61c">

Additionally, I get this error when trying to open the extension manager:
```
Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/__init__.py", line 39, in <module>
    import gi
  File "/opt/homebrew/lib/python3.10/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/gi/_gi.cpython-310-darwin.so, 0x0002): Symbol not found: _g_assertion_message_cmpint
  Referenced from: <94530370-509A-396B-BA9A-36FF174A8F76> /opt/homebrew/lib/python3.10/site-packages/gi/_gi.cpython-310-darwin.so
  Expected in:     <E28BE233-BA84-3CFA-B97E-0F5B2C5A502E> /Applications/Inkscape.app/Contents/Resources/lib/libglib-2.0.0.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkman/inkman/manage_extensions.py", line 29, in <module>
    from inkex import gui
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/gui/__init__.py", line 50, in <module>
    raise DependencyError(
inkex.utils.DependencyError: You are missing the required libraries for Gtk. Please report this problem to the Inkscape developers.
```

I have tried a few troubleshooting tips, including running the following commands in the 3.10 interpreter, which have not returned any errors:
```
>>> import gi
>>> gi.require_version("Gtk", "3.0")
>>> from gi.repository import Gtk
>>> from gi.repository import Gdk
>>> from gi.repository import GdkPixbuf
>>>
```

I have gone through the following steps to install the secondary Python interpreter:

1. brew install python@3.10
2. brew install python-tk@3.10
3. brew install numpy
4. brew install pygobject3
5. $(brew --prefix)/opt/python@3.10/libexec/bin/pip install lxml
6. $(brew --prefix)/opt/python@3.10/libexec/bin/pip install cssselect
7. /opt/homebrew/opt/python@3.10/libexec/bin/pip3 install PyGObject
8. /opt/homebrew/opt/python@3.10/libexec/bin/pip3 install numpy

**Logfile**
[textext.log](https://github.com/textext/textext/files/14813081/textext.log)

**System information**

- TexText version: 1.10.2
- Inkscape version: 1.3.2
- Operating system: [MacOS Sonoma 14.0]

Thank you so much for your help!

**Comment by jcwinkler** [comment]
Hmm, that's strange. TexText falls back to TkInter since GTK does not work (so the extension manager crashes). I can only speculate that something is going wrong in the shared libraries. But why this works during setup but not when opening from Inkscape - I do not know. I am sorry.
